### PR TITLE
Debug UART added (output to blue LED), print redirected to UART.

### PR DESCRIPTION
**Pull request by skiphansen**
working 115200 UART !

### CODE REVIEW

**Comment by zephray** [comment]
Optical UART?

**Comment by skiphansen** [comment]
Sure!  But I'm lazy so I'm hooking a wire to the blue LED instead.  Seriously the Pano doesn't have many pins that are easily accessible, but the LEDs are...

**Comment by tomverbeure** [comment]
I think it's high time that we refactor top_defines.h such that it only contains the base address of each APB block, but move the individual register declarations to the block owner.

E.g. uart.h contains the UART registers.

Tom

**Comment by skiphansen** [comment]
Sounds good to me.

Skip

**Pull request merged**
